import express from 'express';
import cors from 'cors';
import cookieParser from 'cookie-parser';
import bcrypt from 'bcryptjs';
import path from 'node:path';
import fs from 'node:fs';
import { db, seed } from './db.js';
import { attachUser, login, logout, requireAuth, requireRole } from './auth.js';
import { audit, bookingView, callNext, createBooking, notify, recommendation, transactionRef, transitionBooking } from './services.js';

seed();
const app = express();
const allowedOrigins = [process.env.FRONTEND_ORIGIN, 'http://localhost:5173', 'http://127.0.0.1:5173'].filter(Boolean);
app.use(cors({ origin: (origin, callback) => callback(null, !origin || allowedOrigins.includes(origin)), credentials: true }));
app.use(express.json()); app.use(cookieParser()); app.use(attachUser);
const distPath = path.resolve('dist');
if (fs.existsSync(distPath)) app.use(express.static(distPath));
const send = (res, body, status = 200) => res.status(status).json(body);
const fail = (res, error) => send(res, { error: error.message || 'Request failed.' }, error.status || 500);

app.get('/api/health', (_req, res) => send(res, { ok: true, database: 'sqlite' }));
app.post('/api/auth/login', (req, res) => { try { if (!req.body?.email || !req.body?.password) return send(res, { error: 'Email and password are required.' }, 400); const result = login(req.body.email, req.body.password); res.cookie('krishisetu_session', result.token, { httpOnly: true, sameSite: 'lax', secure: process.env.NODE_ENV === 'production', maxAge: 8 * 60 * 60 * 1000 }); return send(res, result); } catch (error) { return fail(res, error); } });
app.post('/api/auth/logout', (req, res) => { logout(req.cookies?.krishisetu_session); res.clearCookie('krishisetu_session'); return send(res, { ok: true }); });
app.get('/api/auth/me', requireAuth, (req, res) => send(res, { user: req.user }));
app.post('/api/auth/register', (req, res) => { try { const { name, email, password, mobile, state, district, village, language = 'English' } = req.body || {}; if (!name || !email || !password || !mobile || !state || !district || !village) return send(res, { error: 'Name, email, password, mobile, state, district, and village are required.' }, 400); if (!/^\S+@\S+\.\S+$/.test(email) || !/^\d{10}$/.test(mobile)) return send(res, { error: 'Enter a valid email and 10-digit demo mobile number.' }, 400); const result = db.prepare('INSERT INTO users (name,email,password_hash,role,mobile,state,district,village,language) VALUES (?,?,?,?,?,?,?,?,?)').run(name, email, bcrypt.hashSync(password, 10), 'FARMER', mobile, state, district, village, language); notify(result.lastInsertRowid, 'Welcome to KrishiSetu', 'Your farmer account has been created.'); audit(result.lastInsertRowid, 'REGISTER', 'user', result.lastInsertRowid, null, { role: 'FARMER' }); return send(res, { id: result.lastInsertRowid }, 201); } catch (error) { return send(res, { error: error.code === 'SQLITE_CONSTRAINT_UNIQUE' ? 'An account with this email already exists.' : 'Unable to create account.' }, 409); } });

app.get('/api/centres', requireAuth, (req, res) => { const centres = db.prepare(`SELECT c.*, COUNT(CASE WHEN b.status IN ('BOOKED','CHECKED_IN','WAITING','CALLED','PROCESSING') THEN 1 END) active_bookings, COUNT(CASE WHEN b.status IN ('CHECKED_IN','WAITING','CALLED','PROCESSING') THEN 1 END) queue_count FROM centres c LEFT JOIN bookings b ON b.centre_id=c.id WHERE c.active=1 GROUP BY c.id ORDER BY c.name`).all().map((c) => ({ ...c, utilization: Math.round((c.active_bookings / c.daily_capacity) * 100), wait: Math.round(c.queue_count * c.average_processing_minutes / c.active_counters), status: c.queue_count > 30 || c.active_bookings / c.daily_capacity > .9 ? 'HIGH' : c.queue_count > 15 ? 'MODERATE' : 'LOW', availableSlots: db.prepare("SELECT COUNT(*) count FROM slots s WHERE s.centre_id=? AND s.slot_date='2026-09-12' AND (SELECT COUNT(*) FROM bookings b WHERE b.slot_id=s.id AND b.status NOT IN ('CANCELLED','NO_SHOW')) < s.capacity").get(c.id).count })); return send(res, { centres, recommendation: recommendation(centres) }); });
app.get('/api/crops', requireAuth, (_req, res) => send(res, { crops: db.prepare('SELECT id,name FROM crops ORDER BY name').all() }));
app.get('/api/slots', requireAuth, (req, res) => { const slots = db.prepare(`SELECT s.*, s.capacity - COUNT(CASE WHEN b.status NOT IN ('CANCELLED','NO_SHOW') THEN 1 END) available FROM slots s LEFT JOIN bookings b ON b.slot_id=s.id WHERE s.centre_id=? AND s.slot_date=? GROUP BY s.id ORDER BY s.start_time`).all(Number(req.query.centreId), req.query.date || '2026-09-12'); return send(res, { slots }); });

app.get('/api/farmer/dashboard', requireRole('FARMER'), (req, res) => { const booking = db.prepare("SELECT id FROM bookings WHERE farmer_id=? AND status NOT IN ('CANCELLED','NO_SHOW') ORDER BY id DESC LIMIT 1").get(req.user.id); const notifications = db.prepare('SELECT * FROM notifications WHERE user_id=? ORDER BY id DESC LIMIT 12').all(req.user.id); return send(res, { user: req.user, booking: booking ? bookingView(booking.id) : null, notifications }); });
app.post('/api/bookings', requireRole('FARMER'), (req, res) => { try { const { centreId, cropId, slotId, quantity, quantityUnit = 'quintals' } = req.body || {}; if (!Number.isInteger(Number(centreId)) || !Number.isInteger(Number(cropId)) || !Number.isInteger(Number(slotId)) || !Number(quantity) || Number(quantity) <= 0 || quantityUnit !== 'quintals') return send(res, { error: 'Centre, crop, slot, and a positive quantity in quintals are required.' }, 400); const centre = db.prepare('SELECT id FROM centres WHERE id=? AND active=1').get(centreId); const crop = db.prepare('SELECT id FROM crops WHERE id=?').get(cropId); if (!centre || !crop) return send(res, { error: 'Centre or crop does not exist.' }, 400); return send(res, { booking: createBooking({ farmerId: req.user.id, centreId: Number(centreId), cropId: Number(cropId), slotId: Number(slotId), quantity: Number(quantity), quantityUnit, actorId: req.user.id }) }, 201); } catch (error) { return fail(res, error); } });
app.delete('/api/bookings/:id', requireRole('FARMER'), (req, res) => { try { const booking = db.prepare('SELECT * FROM bookings WHERE id=? AND farmer_id=?').get(Number(req.params.id), req.user.id); if (!booking) return send(res, { error: 'Booking not found.' }, 404); const updated = transitionBooking({ bookingId: booking.id, nextStatus: 'CANCELLED', actorId: req.user.id }); return send(res, { booking: updated }); } catch (error) { return fail(res, error); } });

app.get('/api/operator/queue', requireRole('OPERATOR','ADMIN'), (req, res) => { const centreId = req.user.role === 'OPERATOR' ? req.user.centreId : Number(req.query.centreId); if (!centreId) return send(res, { error: 'Centre is required.' }, 400); const queue = db.prepare(`SELECT b.id,b.token,b.status,b.quantity,u.name farmer_name,cr.name crop_name,s.start_time,s.end_time,q.position,q.estimated_wait_minutes FROM bookings b JOIN users u ON u.id=b.farmer_id JOIN crops cr ON cr.id=b.crop_id JOIN slots s ON s.id=b.slot_id JOIN queue_entries q ON q.booking_id=b.id WHERE b.centre_id=? AND b.status NOT IN ('CANCELLED','NO_SHOW','COMPLETED') ORDER BY q.position`).all(centreId); return send(res, { queue }); });
app.post('/api/operator/bookings/:id/check-in', requireRole('OPERATOR'), (req, res) => { try { const booking = db.prepare('SELECT * FROM bookings WHERE id=? AND centre_id=?').get(Number(req.params.id), req.user.centreId); if (!booking) return send(res, { error: 'Booking not found at your centre.' }, 404); return send(res, { booking: transitionBooking({ bookingId: booking.id, nextStatus: 'CHECKED_IN', actorId: req.user.id }) }); } catch (error) { return fail(res, error); } });
app.post('/api/operator/call-next', requireRole('OPERATOR'), (req, res) => { try { return send(res, { booking: callNext(req.user.id, req.user.centreId) }); } catch (error) { return fail(res, error); } });
app.post('/api/operator/bookings/:id/advance', requireRole('OPERATOR'), (req, res) => { try { const current = db.prepare('SELECT * FROM bookings WHERE id=? AND centre_id=?').get(Number(req.params.id), req.user.centreId); if (!current) return send(res, { error: 'Booking not found at your centre.' }, 404); const next = current.status === 'CALLED' ? 'PROCESSING' : current.status === 'PROCESSING' ? 'COMPLETED' : null; if (!next) return send(res, { error: 'This booking must be called before processing.' }, 409); if (next === 'COMPLETED' && (!Number(req.body.actualQuantity) || Number(req.body.actualQuantity) <= 0)) return send(res, { error: 'Actual quantity is required to complete procurement.' }, 400); return send(res, { booking: transitionBooking({ bookingId: current.id, nextStatus: next, actorId: req.user.id, actualQuantity: Number(req.body.actualQuantity), qualityStatus: req.body.qualityStatus }) }); } catch (error) { return fail(res, error); } });
app.post('/api/operator/payments/:bookingId/complete', requireRole('OPERATOR'), (req, res) => { try { const booking = db.prepare('SELECT b.*,p.status payment_status FROM bookings b JOIN payments p ON p.booking_id=b.id WHERE b.id=? AND b.centre_id=?').get(Number(req.params.bookingId), req.user.centreId); if (!booking || booking.status !== 'COMPLETED') return send(res, { error: 'Procurement must be completed first.' }, 409); const ref = transactionRef(); db.prepare("UPDATE payments SET status='COMPLETED',transaction_ref=?,completed_at=CURRENT_TIMESTAMP WHERE booking_id=?").run(ref, booking.id); notify(booking.farmer_id, 'Payment credited', `Payment has been credited. Transaction ${ref}.`); audit(req.user.id, 'PAYMENT_COMPLETED', 'payment', booking.id, { status: booking.payment_status }, { status: 'COMPLETED', ref }); return send(res, { payment: db.prepare('SELECT * FROM payments WHERE booking_id=?').get(booking.id) }); } catch (error) { return fail(res, error); } });

app.get('/api/notifications', requireAuth, (req, res) => send(res, { notifications: db.prepare('SELECT * FROM notifications WHERE user_id=? ORDER BY id DESC').all(req.user.id) }));
app.post('/api/notifications/:id/read', requireAuth, (req, res) => { const result = db.prepare('UPDATE notifications SET read_at=CURRENT_TIMESTAMP WHERE id=? AND user_id=?').run(Number(req.params.id), req.user.id); return send(res, { updated: result.changes > 0 }); });
app.get('/api/admin/analytics', requireRole('ADMIN'), (_req, res) => { const totals = db.prepare(`SELECT (SELECT COUNT(*) FROM users WHERE role='FARMER') farmers,(SELECT COUNT(*) FROM bookings WHERE status NOT IN ('CANCELLED','NO_SHOW','COMPLETED')) active_bookings,(SELECT COUNT(*) FROM centres WHERE active=1) centres,(SELECT COALESCE(SUM(amount),0) FROM payments WHERE status='COMPLETED') payments,(SELECT COALESCE(SUM(actual_quantity),0) FROM procurements WHERE stage='PROCUREMENT_COMPLETED') procurement`).get(); const daily = db.prepare("SELECT substr(created_at,1,10) day,COUNT(*) count FROM bookings GROUP BY day ORDER BY day DESC LIMIT 7").all().reverse(); const centreStats = db.prepare(`SELECT c.name,COUNT(b.id) bookings,COALESCE(ROUND(AVG(q.estimated_wait_minutes)),0) avg_wait,c.daily_capacity FROM centres c LEFT JOIN bookings b ON b.centre_id=c.id LEFT JOIN queue_entries q ON q.booking_id=b.id GROUP BY c.id ORDER BY avg_wait`).all(); return send(res, { totals, daily, centreStats }); });

if (fs.existsSync(distPath)) app.get(/^(?!\/api).*/, (_req, res) => res.sendFile(path.join(distPath, 'index.html')));
app.use((_req, res) => send(res, { error: 'Not found.' }, 404));
app.use((error, _req, res, _next) => { console.error(error); return send(res, { error: 'Internal server error.' }, 500); });
const port = Number(process.env.PORT || 4000);
if (process.argv[1]?.endsWith('index.js')) app.listen(port, () => console.log(`KrishiSetu API listening on http://localhost:${port}`));
export { app };
